### ISSUE TITLE
Compile error with gcc 8.1.1

### ISSUE THREAD

**Issue by thesourcehim** [stephenjsweeney/blobwarsAttrition#18]
src/system/i18n.c: In function «setLanguage»:
src/system/i18n.c:85:17: error: «%s» directive writing up to 1023 bytes into a region of size 1006 [-Werror=format-overflow=]
  sprintf(c, "%s/%s/LC_MESSAGES/%s.mo", LOCALE_DIR, language, applicationName);
                 ^~                                 ~~~~~~~~
src/system/i18n.c:85:2: warning: «sprintf» output 35 or more bytes (assuming 1058) into a destination of size 1024
  sprintf(c, "%s/%s/LC_MESSAGES/%s.mo", LOCALE_DIR, language, applicationName);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/system/i18n.c:108:18: error: «%s» directive writing up to 1023 bytes into a region of size 1006 [-Werror=format-overflow=]
   sprintf(c, "%s/%s/LC_MESSAGES/%s.mo", LOCALE_DIR, language, applicationName);
                  ^~                                 ~~~~~~~~
src/system/i18n.c:108:3: warning: «sprintf» output 35 or more bytes (assuming 1058) into a destination of size 1024
   sprintf(c, "%s/%s/LC_MESSAGES/%s.mo", LOCALE_DIR, language, applicationName);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by stephenjsweeney** [comment]
Please try the update in develop and let me know. I'm on 4.8.5 over here ;)
