### ISSUE TITLE
make fails with following error

### ISSUE THREAD

**Issue by timsoftgit** [stephenjsweeney/blobwarsAttrition#21]
```
gcc -O2 -fPIC `sdl2-config --cflags` -DVERSION=1.2 -DREVISION=0 -DDATA_DIR=\"/usr/share/games/blobwarsAttrition\" -DLOCALE_DIR=\"/usr/share/locale\" -g -lefence -fms-extensions -std=gnu11 -c -o bin/destructable.o src/entities/misc/destructable.c
In file included from /usr/include/string.h:630:0,
                 from src/game/../common.h:23,
                 from src/game/credits.h:21,
                 from src/game/credits.c:21:
src/game/credits.h:37:14: error: expected identifier or '(' before '__extension_ '
 extern char *strtok_r(char *str, const char *delim, char **nextp);
              ^
common.mk:64: recipe for target 'bin/credits.o' failed
make: *** [bin/credits.o] Error 1


my make commands are as follows ( I am using the paid version - ie includes the data )
make CFLAGS="$SLKCFLAGS" DATA_DIR="/usr/share/games/$PRGNAM"
make install DESTDIR=$PKG DATA_DIR="/usr/share/games/$PRGNAM"
(where SLKCFLAGS is "-O2 -fPIC" PRGNAM is "blobwarsAttrition" and PKG is "/tmp/SBo/package-blobwarsAttrition" )

```

**Comment by stephenjsweeney** [comment]
Could you remove the 

extern char *strtok_r(char *str, const char *delim, char **nextp);

line and try compiling again. That might be conflicting with a strtok_r already defined in string.h.

(line 37 in src/game/credits.h)

**Comment by timsoftgit** [comment]
when I do that, it then gets stuck here...
gcc -O2 -fPIC `sdl2-config --cflags` -DVERSION=1.2 -DREVISION=0 -DDATA_DIR=\"/usr/share/games/blobwarsAttrition\" -DLOCALE_DIR=\"/usr/share/locale\" -g -lefence -fms-extensions -std=gnu11 -c -o bin/weapons.o src/combat/weapons.c
In file included from /usr/include/string.h:630:0,
                 from src/util/../common.h:23,
                 from src/util/util.h:21,
                 from src/util/util.c:21:
src/util/util.c:113:7: error: expected identifier or '(' before '__extension__'
 char *strtok_r(char *str, const char *delim, char **nextp)
       ^
common.mk:64: recipe for target 'bin/util.o' failed

**Comment by stephenjsweeney** [comment]
Hmm, it's probably because of the existing strtok_r.

If you rename that function to strtok_rr does that fix the issue?

**Comment by timsoftgit** [comment]
thanks, that seems to have fixed it. 
adding 
sed -i "/nextp/d" src/game/credits.h
sed -i 's/*strtok_r/*strtok_rr/g' src/util/util.c
before the make commands lets it complete
 I did have a little problem in that I am testing the build in a vm which is limited to 600x800 resolution so the right hand side is off-screen. Will the game be playable in lower resolutions?

**Comment by stephenjsweeney** [comment]
1280 x 720 is the minimum, unfortunately.

Any reason you're playing in a VM?

**Comment by stephenjsweeney** [comment]
If you happen to be playing on Windows, there's an experimental Windows release up on itch.io.

I've only tested that the game can launch (via Wine), and load and save games.

**Comment by timsoftgit** [comment]
i build lots of packages in a vm to ensure the environment is "clean". it allows me to test installing something and not worry if things get messed up. for example some installers (make install) may take a DESTDIR, but may ignore it and install icons and .desktop files locally, which is not so helpful if you are creating a package to be installed elsewhere. (no problems in that regard with blobwarsAttrition, I haste to add). I created the slackbuilds for blobwars, starfighter, edgar and tbftss, so when I saw the attrition one, I thought I would give it a go for my own personal use, even if it can't go on sbo without a download link (which I obviously can't provide as it is a revenue stream for you). You're more than welcome to use the slackbuild when I've finished it if you want to provide a slackware package for those buying the game data, or just the script and files for those wanting to create a package themselves once they have bought the data version.
I haven't checked, but is SDL2 the only dependency?, (or do I need any of SDL2_mixer, SDL2_image, SDL2_ttf or/and SDL2_net as well?).

**Comment by timsoftgit** [comment]
[blobwarsAttrition.tar.gz](https://github.com/stephenjsweeney/blobwarsAttrition/files/3652409/blobwarsAttrition.tar.gz)
slackbuild script for blobwarsAttrition :-)

**Comment by timsoftgit** [comment]
correction regarding my second point. vm is not limited to 600x800, that is just the initial resolution. it can be changed in kde menu settings-system settings-display and monitor-size and orientation, and 1280x720 is available and works, as does 1920x1080 and 1280x1024
