### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by thesourcehim** [stephenjsweeney/blobwarsAttrition#3]
I'm trying to build the game for linux fedora 27 x86_64 and I get the following error:

src/system/draw.c: In fuction «saveScreenshot»:
src/system/draw.c:269:25: error: «%d» directive writing between 1 and 11 bytes into a region of size between 0 and 1023 [-Werror=format-overflow=]
   sprintf(filename, "%s/%d/%s.png", app.saveDir, game.saveSlot, name);
                         ^~
src/system/draw.c:269:3: warning: «sprintf» output 8 or more bytes (assuming 1031) into a destination of size 1024
   sprintf(filename, "%s/%d/%s.png", app.saveDir, game.saveSlot, name);

**Comment by stephenjsweeney** [comment]
Please try building the latest code in develop. I've added MAX_PATH to hopefully mitigate this one.

**Comment by thesourcehim** [comment]
Compiles fine from develop branch

**Comment by stephenjsweeney** [comment]
Closing this as issue seems to be resolved.
