### ISSUE TITLE
Several crashes

### ISSUE THREAD

**Issue by thesourcehim** [stephenjsweeney/blobwarsAttrition#4]
Found several game crashes under linux:
1. Game always crashes when I move the right stick on my xbox 360 controller
2. Game crashes when I pickup heart in Beach Front #1 and trophy alert appears from top left. It seems game crashes while trying to save screenshot, when trophy screenshot is disabled, no cash.

**Comment by thesourcehim** [comment]
Right stick doesn't crash game anymore, I'll test with trophies, when I get one.

**Comment by thesourcehim** [comment]
bt full
#0  0x00007ffff6961660 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff6962c41 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff69a3f17 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff69aa21a in malloc_printerr () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff69aa75c in munmap_chunk () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007ffff7b30e3f in SDL_free_REAL () from /lib64/libSDL2-2.0.so.0
No symbol table info available.
#6  0x00007ffff7b12dab in GL_RenderReadPixels () from /lib64/libSDL2-2.0.so.0
No symbol table info available.
#7  0x00007ffff7b0e77d in SDL_RenderReadPixels_REAL () from /lib64/libSDL2-2.0.so.0
No symbol table info available.
#8  0x000000000040a894 in saveScreenshot (name=0x29db3e0 "HEART") at src/system/draw.c:277
        filename = "/home/thesource/.local/share/blobwarsAttrition/1/HEART.png\000\002\000\000\000\000\230\341\233\002\000\000\000\000\234\341\233\002\000\000\000\000\240\341\233\002\000\000\000\000\244\341\233\002\000\000\000\000\250\341\233\002\000\000\000\000\254\341\233\002\000\000\000\000\260\341\233\002\000\000\000\000\264\341\233\002\000\000\000\000\b\342\233\002\000\000\000\000\\\342\233\002\000\000\000\000\260\342\233\002\000\000\000\000\274\341\233\002\000\000\000\000\270\341\233\002\000\000\000\000\300\341\233\002\000\000\000\000\304\341\233\002\000\000\000\000\310\341\233\002\000\000\000\000\320\341\233\002\000\000\000\000"...
        screenshot = 0x30914c0
#9  0x000000000042c9a5 in saveTrophyScreenshot () at src/game/trophies.c:339
No locals.
#10 0x000000000041fc60 in main (argc=1, argv=0x7fffffffdb38) at src/main.c:70
        then = 122735
        nextSecond = 123368
        frames = 22

**Comment by stephenjsweeney** [comment]
Reading the docs, it seems that even I shouldn't be able to save a screenshot, as the back buffer is set up as SDL_TEXTUREACCESS_TARGET and not SDL_TEXTUREACCESS_STREAMING.

I think it might be best to ditch the feature, as it's not really all that useful ;)

**Comment by thesourcehim** [comment]
That cleared the issue, thank you

**Comment by stephenjsweeney** [comment]
Closing this as issue seems to be resolved.
