### ISSUE TITLE
Wrong items are activated in main menu

### ISSUE THREAD

**Issue by thesourcehim** [stephenjsweeney/blobwarsAttrition#6]
I just noticed some strange thing: from main menu select 'load game', but then select 'cancel' to go back, then select 'options' - the game will actually load instead of going to options.

**Comment by stephenjsweeney** [comment]
I've given this a go and can't reproduce it. Can you do so consistently? My steps are:

1. Start the game.
2. Choose Load (I've got all five slots in use).
3. Select Cancel.
4. Select Options.

It works as expect. Is there anything specific you're doing first?

**Comment by thesourcehim** [comment]
Some should remind me not to play at night instead of sleeping, apparently I was pressing 'continue', not 'options', sorry about that.

**Comment by stephenjsweeney** [comment]
No problem ;)
