### ISSUE TITLE
Unable to progress, possibly due to a crash on level Greenlands 3

### ISSUE THREAD

**Issue by noahadvs** [stephenjsweeney/blobwarsAttrition#9]
In one of the Greenlands missions (maybe Greenlands 3, I killed a lazer blob squad leader to finish it), I had a crash right as I completed the mission. As I understand the game, stuff like doors and computers do not need to be unlocked again after level completion. However, even though the mission was marked as partially completed when I re-opened the game, I had to re-unlock everything. Unfortunately, I can't give any more details about the crash and I have not encountered one since then.

Can you confirm that my save data is bugged and that I'm not just overlooking something? If my save data is bugged, how do I get it to the state it should be in? They're all JSON files, so I assume I can just modify my save data to get my items back.

My save data from `~/.local/share/blobwarsAttrition`:
[blobwarsAttrition-save.tar.gz](https://github.com/stephenjsweeney/blobwarsAttrition/files/1940452/blobwarsAttrition-save.tar.gz)

My inventory: 2 silver keys, 2 blue keycards, 3 yellow keycards, 3 gold keys

I've fully completed all missions up to
* Outpost 2 (partially completed, I need 1 bronze key)
* Outpost 4 (incomplete, I might need only 1 bronze key)
* Greenlands 5 (partially completed, I need 3 bronze keys)
* Underground 5 (incomplete, don't have enough keycards to exit)

**Comment by stephenjsweeney** [comment]
Unfortunately, it looks like the crash has put your game into an inconsistent state. The only solution now would be to restart. The bronze keys that you're missing are on Underground 5, but as you said you now have the wrong number of keycards.

I will investigate saving the game atomically, to try to mitigate these crashes.

**Comment by noahadvs** [comment]
I can't just edit `game.json` to give myself as many cards or keys as I need to progress?

**Comment by stephenjsweeney** [comment]
You can do so, yes. You would just need to edit the save file to do so. Sorry, I thought you meant without doing so.

You can also run the game with -keys to allow you to open any door and use any card reader, without needing to have the key in your inventory.

**Comment by noahadvs** [comment]
Ok, thanks!
